# Generated by Django 5.1.2 on 2024-11-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=128)),
                ("qty", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("when", models.DateTimeField()),
            ],
        ),
    ]
