# Generated by Django 5.1.2 on 2024-11-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("supply", "Supply"), ("sale", "Sale")],
                default="supply",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
