services:
  project:
    build:
      context: ./project
    container_name: "439FC20B0EAA"
    command: >
      sh -c "python manage.py migrate &&
      python manage.py runserver"
    volumes:
      - ./project:/app
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
